//
//  BTTSetup.swift
//  blue-triangle
//
//  Created by Ashok Singh on 26/05/26.
//

// Sources/BTTSetup/BTTSetup.swift
// ─────────────────────────────────────────────────────────────────────────────
// BlueTriangle SDK — One-time project setup tool
//
// Usage (from SDK root or app project root):
//   swift run BTTSetup
//   swift run BTTSetup /path/to/MyApp
//   swift run BTTSetup --dry-run
//   swift run BTTSetup --phases-only
//   swift run BTTSetup --help
// ─────────────────────────────────────────────────────────────────────────────

// Sources/BTTSetup/BTTSetup.swift
// ─────────────────────────────────────────────────────────────────────────────
// BlueTriangle SDK — One-time project setup tool
//
// Usage (from SDK root or app project root):
//   swift run BTTSetup
//   swift run BTTSetup /path/to/MyApp
//   swift run BTTSetup --dry-run
//   swift run BTTSetup --phases-only
//   swift run BTTSetup --help
// ─────────────────────────────────────────────────────────────────────────────

#if os(macOS)
import Foundation

// MARK: - ANSI Colors

enum C {
    static let reset  = "\u{001B}[0m"
    static let bold   = "\u{001B}[1m"
    static let green  = "\u{001B}[0;32m"
    static let yellow = "\u{001B}[1;33m"
    static let red    = "\u{001B}[0;31m"
    static let blue   = "\u{001B}[0;34m"
    static let cyan   = "\u{001B}[0;36m"
}

func step(_ msg: String)  { print("\n\(C.bold)\(C.blue)▶ \(msg)\(C.reset)") }
func ok(_ msg: String)    { print("  \(C.green)✅ \(msg)\(C.reset)") }
func warn(_ msg: String)  { print("  \(C.yellow)⚠️  \(msg)\(C.reset)") }
func info(_ msg: String)  { print("  \(C.cyan)ℹ️  \(msg)\(C.reset)") }
func dry(_ msg: String)   { print("  \(C.yellow)[DRY-RUN] \(msg)\(C.reset)") }
func fail(_ msg: String)  { print("  \(C.red)❌ \(msg)\(C.reset)") }

// MARK: - Script Templates

let injectScript = #"""
#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# btt-inject.sh  —  BlueTriangle PRE-BUILD injection
# Auto-generated by BTTSetup. Do not edit manually.
# ─────────────────────────────────────────────────────────────────
set -e

ARCH=$(uname -m)
SRC_ROOT="$SRCROOT"

echo "🔍 Resolving BTTInstrumentor..."

DERIVED_DATA=$(dirname "$BUILD_DIR")/..

BUNDLE=$(find \
    "$DERIVED_DATA/SourcePackages/artifacts" \
    "$DERIVED_DATA/SourcePackages/checkouts" \
    "$SRC_ROOT/../../../" \
    -maxdepth 8 \
    -name "BTTInstrumentor.artifactbundle" \
    -type d 2>/dev/null | head -1)

if [ -z "$BUNDLE" ]; then
    echo "⚠️ BTTInstrumentor.artifactbundle not found — skipping injection"
    exit 0
fi

echo "📦 Bundle: $BUNDLE"

BINARY=$(python3 - <<EOF
import json, os, sys
bundle = "$BUNDLE"
arch = "$ARCH"
with open(os.path.join(bundle, "info.json")) as f:
    data = json.load(f)
variants = data.get("artifacts", {}).get("BTTInstrumentor", {}).get("variants", [])
for v in variants:
    if any(arch in t for t in v.get("supportedTriples", [])):
        print(os.path.join(bundle, v["path"]))
        sys.exit(0)
sys.exit(1)
EOF
)

if [ -z "$BINARY" ] || [ ! -f "$BINARY" ]; then
    echo "⚠️ Binary not found for arch: $ARCH — skipping"
    exit 0
fi

echo "⚙️ Binary: $BINARY"
chmod +x "$BINARY"

# Restore any leftover backups from a crashed previous build
find "$SRC_ROOT" -name "*.swift.bttbackup" \
    ! -path "*/Pods/*" ! -path "*/.build/*" ! -path "*/DerivedData/*" \
    | while read -r BACKUP; do
        ORIGINAL="${BACKUP%.bttbackup}"
        cp "$BACKUP" "$ORIGINAL"
        rm "$BACKUP"
        echo "♻️  Restored leftover: $(basename "$ORIGINAL")"
    done

echo "🔧 BTT Injecting (arch: $ARCH)..."

find "$SRC_ROOT" -name "*.swift" \
    ! -path "*/Pods/*" \
    ! -path "*/.build/*" \
    ! -path "*/DerivedData/*" \
    ! -path "*/BTTInstrumentor/*" \
    | while read -r FILE; do
        "$BINARY" "$FILE"
    done

echo "✅ Injection complete"
"""#

let restoreScript = #"""
#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# btt-restore.sh  —  BlueTriangle POST-BUILD restore
# Auto-generated by BTTSetup. Do not edit manually.
# ─────────────────────────────────────────────────────────────────
set -e

ARCH=$(uname -m)
SRC_ROOT="$SRCROOT"

echo "🔄 BTT Restoring files..."

DERIVED_DATA=$(dirname "$BUILD_DIR")/..

BUNDLE=$(find \
    "$DERIVED_DATA/SourcePackages/artifacts" \
    "$DERIVED_DATA/SourcePackages/checkouts" \
    "$SRC_ROOT/../../../" \
    -maxdepth 8 \
    -name "BTTInstrumentor.artifactbundle" \
    -type d 2>/dev/null | head -1)

if [ -z "$BUNDLE" ]; then
    echo "⚠️ BTTInstrumentor.artifactbundle not found — skipping restore"
    exit 0
fi

BINARY=$(python3 - <<EOF
import json, os, sys
bundle = "$BUNDLE"
arch = "$ARCH"
with open(os.path.join(bundle, "info.json")) as f:
    data = json.load(f)
variants = data.get("artifacts", {}).get("BTTInstrumentor", {}).get("variants", [])
for v in variants:
    if any(arch in t for t in v.get("supportedTriples", [])):
        print(os.path.join(bundle, v["path"]))
        sys.exit(0)
sys.exit(1)
EOF
)

if [ -z "$BINARY" ] || [ ! -f "$BINARY" ]; then
    echo "⚠️ Binary not found for arch: $ARCH — skipping restore"
    exit 0
fi

chmod +x "$BINARY"

find "$SRC_ROOT" -name "*.swift" \
    ! -path "*/Pods/*" \
    ! -path "*/.build/*" \
    ! -path "*/DerivedData/*" \
    ! -path "*/BTTInstrumentor/*" \
    | while read -r FILE; do
        "$BINARY" "$FILE" --restore
    done

echo "✅ Restore complete"
"""#

// MARK: - File System Helpers

let fm = FileManager.default

func writeScript(_ content: String, to path: String, dryRun: Bool) -> Bool {
    if dryRun {
        dry("Would write: \(path)")
        return true
    }
    let dir = (path as NSString).deletingLastPathComponent
    do {
        try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        try content.write(toFile: path, atomically: true, encoding: .utf8)
        // chmod +x
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: path)
        return true
    } catch {
        fail("Could not write \(path): \(error.localizedDescription)")
        return false
    }
}

func findXcodeproj(in root: String) -> String? {
    guard let enumerator = fm.enumerator(
        at: URL(fileURLWithPath: root),
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else { return nil }

    for case let url as URL in enumerator {
        // Don't recurse too deep
        let depth = url.pathComponents.count - URL(fileURLWithPath: root).pathComponents.count
        if depth > 4 { enumerator.skipDescendants(); continue }
        if url.pathExtension == "xcodeproj" { return url.path }
    }
    return nil
}

func rubyAvailable() -> Bool {
    let task = Process()
    task.launchPath = "/usr/bin/which"
    task.arguments = ["ruby"]
    task.standardOutput = Pipe()
    task.standardError = Pipe()
    try? task.run()
    task.waitUntilExit()
    return task.terminationStatus == 0
}

func gemInstalled(_ name: String) -> Bool {
    let task = Process()
    task.launchPath = "/usr/bin/gem"
    task.arguments = ["list", name, "-i"]
    let pipe = Pipe()
    task.standardOutput = pipe
    task.standardError = Pipe()
    try? task.run()
    task.waitUntilExit()
    let out = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
    return out.trimmingCharacters(in: .whitespacesAndNewlines) == "true"
}

@discardableResult
func shell(_ args: [String]) -> Int32 {
    let task = Process()
    task.launchPath = args[0]
    task.arguments = Array(args.dropFirst())
    try? task.run()
    task.waitUntilExit()
    return task.terminationStatus
}

// MARK: - Xcode Phase Injection via Ruby

let rubyScript = #"""
require 'xcodeproj'

proj_path      = ARGV[0]
inject_name    = ARGV[1]
restore_name   = ARGV[2]
inject_rel     = ARGV[3]
restore_rel    = ARGV[4]

project  = Xcodeproj::Project.open(proj_path)
modified = false

project.targets.each do |target|
  next unless target.is_a?(Xcodeproj::Project::Object::PBXNativeTarget)
  next unless target.product_type == "com.apple.product-type.application"

  existing = target.build_phases.map(&:display_name)

  unless existing.include?(inject_name)
    phase = target.new_shell_script_build_phase(inject_name)
    phase.shell_script      = "bash \"${SRCROOT}/#{inject_rel}\""
    phase.show_env_vars_in_log = "0"
    compile_idx = target.build_phases.index { |p|
      p.is_a?(Xcodeproj::Project::Object::PBXSourcesBuildPhase)
    }
    target.build_phases.move(phase, compile_idx || 0)
    puts "  ✅ Added '#{inject_name}' → #{target.name}"
    modified = true
  else
    puts "  ℹ️  '#{inject_name}' already present in #{target.name}"
  end

  unless existing.include?(restore_name)
    phase = target.new_shell_script_build_phase(restore_name)
    phase.shell_script         = "bash \"${SRCROOT}/#{restore_rel}\""
    phase.show_env_vars_in_log = "0"
    puts "  ✅ Added '#{restore_name}' → #{target.name}"
    modified = true
  else
    puts "  ℹ️  '#{restore_name}' already present in #{target.name}"
  end
end

if modified
  project.save
  puts "\n  💾 Project saved."
else
  puts "\n  ℹ️  No changes — phases already configured."
end
"""#

// MARK: - Main

func printHelp() {
    print("""
\(C.bold)BTTSetup — BlueTriangle SDK project setup\(C.reset)

\(C.bold)USAGE\(C.reset)
  swift run BTTSetup [path] [options]

\(C.bold)ARGUMENTS\(C.reset)
  path            Path to the app project root (default: current directory)

\(C.bold)OPTIONS\(C.reset)
  --dry-run       Preview what would happen, make no changes
  --phases-only   Only add Xcode build phases, skip script generation
  --scripts-only  Only generate Scripts/, skip Xcode phase setup
  --help, -h      Show this message

\(C.bold)EXAMPLES\(C.reset)
  swift run BTTSetup
  swift run BTTSetup ~/MyApp
  swift run BTTSetup --dry-run
""")
}

func run() {
    // ── Parse args ────────────────────────────────────────────────
    var args = CommandLine.arguments.dropFirst()  // drop executable path

    var dryRun      = false
    var doScripts   = true
    var doPhases    = true
    var projectRoot = ""

    for arg in args {
        switch arg {
        case "--dry-run":       dryRun = true
        case "--phases-only":   doScripts = false
        case "--scripts-only":  doPhases = false
        case "--help", "-h":    printHelp(); exit(0)
        default:
            if !arg.hasPrefix("--") && projectRoot.isEmpty {
                projectRoot = arg
            }
        }
    }

    if projectRoot.isEmpty {
        projectRoot = fm.currentDirectoryPath
    }

    // Expand ~ if needed
    if projectRoot.hasPrefix("~") {
        projectRoot = NSHomeDirectory() + projectRoot.dropFirst()
    }

    // ── Banner ────────────────────────────────────────────────────
    print("")
    print("\(C.bold)╔══════════════════════════════════════════╗\(C.reset)")
    print("\(C.bold)║    BlueTriangle SDK  ·  BTTSetup         ║\(C.reset)")
    print("\(C.bold)╚══════════════════════════════════════════╝\(C.reset)")
    print("")
    info("Project root : \(projectRoot)")
    info("Dry run      : \(dryRun)")
    info("Write scripts: \(doScripts)")
    info("Add phases   : \(doPhases)")

    // ── Step 1: Write Scripts/ ────────────────────────────────────
    if doScripts {
        step("Writing injection scripts to Scripts/")

        let scriptsDir  = (projectRoot as NSString).appendingPathComponent("Scripts")
        let injectPath  = (scriptsDir as NSString).appendingPathComponent("btt-inject.sh")
        let restorePath = (scriptsDir as NSString).appendingPathComponent("btt-restore.sh")

        let injectOK  = writeScript(injectScript,  to: injectPath,  dryRun: dryRun)
        let restoreOK = writeScript(restoreScript, to: restorePath, dryRun: dryRun)

        if injectOK  { ok("Scripts/btt-inject.sh") }
        if restoreOK { ok("Scripts/btt-restore.sh") }
    }

    // ── Step 2: Find .xcodeproj ───────────────────────────────────
    guard doPhases else {
        print("")
        print("\(C.bold)\(C.green)╔══════════════════════════════════════════╗\(C.reset)")
        print("\(C.bold)\(C.green)║         Done ✓ Scripts written           ║\(C.reset)")
        print("\(C.bold)\(C.green)╚══════════════════════════════════════════╝\(C.reset)")
        print("")
        return
    }

    step("Locating Xcode project...")

    guard let xcodeproj = findXcodeproj(in: projectRoot) else {
        fail("No .xcodeproj found under \(projectRoot)")
        info("Run from your app project root, or pass the path explicitly:")
        info("  swift run BTTSetup ~/path/to/MyApp")
        exit(1)
    }

    ok("Found: \(xcodeproj)")

    // ── Step 3: Add build phases via Ruby/xcodeproj gem ───────────
    step("Adding Xcode Run Script build phases...")

    guard rubyAvailable() else {
        warn("Ruby not found — cannot add build phases automatically.")
        info("Add them manually in Xcode (see README for instructions).")
        exit(0)
    }

    if !gemInstalled("xcodeproj") {
        info("Installing xcodeproj gem...")
        if !dryRun {
            let result = shell(["/usr/bin/gem", "install", "xcodeproj", "--silent"])
            if result != 0 {
                warn("gem install failed, trying sudo...")
                let sudoResult = shell(["/usr/bin/sudo", "gem", "install", "xcodeproj", "--silent"])
                if sudoResult != 0 {
                    fail("Could not install xcodeproj gem.")
                    info("Install manually:  gem install xcodeproj")
                    info("Then re-run:       swift run BTTSetup --phases-only")
                    exit(1)
                }
            }
            ok("xcodeproj gem installed")
        } else {
            dry("Would install xcodeproj gem")
        }
    }

    if dryRun {
        dry("Would add 'BTT Inject' before Compile Sources in \(xcodeproj)")
        dry("Would add 'BTT Restore' at end of build phases in \(xcodeproj)")
    } else {
        // Write ruby script to a temp file
        let tmpRuby = NSTemporaryDirectory() + "btt_phases.rb"
        try? rubyScript.write(toFile: tmpRuby, atomically: true, encoding: .utf8)

        let result = shell([
            "/usr/bin/ruby", tmpRuby,
            xcodeproj,
            "BTT Inject",
            "BTT Restore",
            "Scripts/btt-inject.sh",
            "Scripts/btt-restore.sh"
        ])

        try? fm.removeItem(atPath: tmpRuby)

        if result != 0 {
            fail("Ruby script failed (exit \(result))")
            info("Add phases manually — see README.")
            exit(1)
        }
    }

    // ── Done ──────────────────────────────────────────────────────
    print("")
    print("\(C.bold)\(C.green)╔══════════════════════════════════════════╗\(C.reset)")
    print("\(C.bold)\(C.green)║         Setup Complete 🎉                ║\(C.reset)")
    print("\(C.bold)\(C.green)╚══════════════════════════════════════════╝\(C.reset)")
    print("")

    if dryRun {
        warn("Dry-run — no files were written or modified.")
    } else {
        print("  \(C.green)BlueTriangle is ready. What was done:\(C.reset)")
        print("")
        print("  1. \(C.bold)Scripts/btt-inject.sh\(C.reset)  created  (pre-build)")
        print("  2. \(C.bold)Scripts/btt-restore.sh\(C.reset) created  (post-build)")
        print("  3. \(C.bold)BTT Inject\(C.reset) phase added before Compile Sources")
        print("  4. \(C.bold)BTT Restore\(C.reset) phase added at end of build phases")
        print("")
        print("  \(C.cyan)Next:\(C.reset)  Build your project in Xcode — that's it.")
    }
    print("")
}

run()

#else
// BTTSetup is a macOS-only developer tool.
// It cannot run on iOS, tvOS, or watchOS.
@_silgen_name("main") func main() {}
#endif
