name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Type of release
        type: choice
        required: true
        options:
          - patch
          - minor
          - major

env:
  VERSION-FILE-PATH: 'Sources/BlueTriangle/Version.swift'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout main
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MIMIC_ACCESS_TOKEN }}

      - name: Bump Version File
        id: bump
        uses: ./.github/actions/bump-version-file
        with:
          version-file-path: ${{ env.VERSION-FILE-PATH }}
          release-type: ${{ inputs.release_type }}

      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version
          commit_user_email: mimic@bluetriangle.com
          commit_author: BTT-Mimic <mimic@bluetriangle.com>


      - name: Create Tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.bump.outputs.version }}',
              sha: '${{ steps.commit.outputs.commit_hash }}'
            })
