name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  xcode_tests:
    name: ${{ matrix.platform }} Tests (Xcode)
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macOS
            destination: "platform=macOS"
          - name: iOS
            destination: "platform=iOS Simulator,name=iPhone 15,OS=17.4"

      steps:
      - uses: actions/checkout@v2
      - name: Test for ${{ matrix.platform }}
        run xcodebuild test -scheme "blue-triangle" -destination ${{ matrix.platform }}
