name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  xcode_tests:
    name: ${{ matrix.platform }} Tests (Xcode)
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macOS
          - "OS=17.4,name=iPhone 15,platform=iOS Simulator"
        scheme: ['blue-triangle']

    steps:
      - uses: actions/checkout@v2
      - name: Build for ${{ matrix.platform }}
        uses: mxcl/xcodebuild@v1
        with:
          xcode: ^15
          platform: ${{ matrix.platform }}
          scheme: ${{ matrix.scheme }}
