name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  xcode_tests:
    name: ${{ matrix.platform }} Tests (Xcode)
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "OS=17.4,name=iPhone 15,platform=iOS Simulator"
    steps:
      - uses: actions/checkout@v2
      - name: Test for ${{ matrix.platform }}
        run: xcodebuild test -scheme "blue-triangle" -destination '${{ matrix.platform }}'
